Make `data.py` ready for classification task
kbressem/trainlib pull request #62
Opened 2022-11-09 19:09 UTC by markus-hinsche

**Changes:**
- Only add to path_cols if it is a path-like object

2022-11-09 19:46 UTC, kbressem commented
I don't think this will work. What if label is a string, e.g. ["active changes", "structural changes"].

This would also be a great use case for try/except/else

2022-11-09 20:41 UTC, markus-hinsche commented
Hmm, you are right. This is not good enough yet. 
`path.exists()` could check if the path exists on the file system. 
Any other ideas?

2022-11-09 20:49 UTC, kbressem commented
Yes. I also thing path exists is needed. Also a nice check for correct paths. Double functionality with just one feature. Awesome 😎

2022-11-09 20:59 UTC, markus-hinsche commented on trainlib/data.py
> +            path = Path(path)
```suggestion
            path = Path(path)
            if not path.exits():
                continue
```

2022-11-09 21:01 UTC, markus-hinsche commented
But it only checks the path at index 0, not all paths

2022-11-09 22:04 UTC, kbressem commented
> But it only checks the path at index 0, not all paths

True, but this would catch errors with data_dir. 
Otherwise check of it ends with `\.[A-Za-z0-9]+`. Still not 100% fool-proof.

2022-11-16 07:38 UTC, kbressem commented
Have a look at #68. It's fixed now. 

Sorry that I've ignored your changes but there were some deeper errors in the viewer classes which needed to be addressed.

2022-11-16 08:10 UTC, kbressem approved these changes
LGTM. But can you address the mypy error? Maybe use `Path` not `PurePath`?

2022-11-16 08:20 UTC, markus-hinsche commented on trainlib/data.py
> +        if isinstance(path, Path) and path.exits():
```suggestion
        if isinstance(path, Path) and path.exists():
```

2022-11-16 10:08 UTC, markus-hinsche commented
Fixed mypy but now unit tests are failing. @kbressem Any idea why?

2022-11-16 12:37 UTC, kbressem requested changes

2022-11-16 12:37 UTC, kbressem commented on tests/test_trainer.py
> +            pass
```suggestion
        shutil.rmtree(self.config.run_id.split("/")[0], ignore_errors=True)
        shutil.rmtree(self.config.model_dir, ignore_errors=True)
        shutil.rmtree(self.config.data.cache_dir, ignore_errors=True)
        ```

2022-11-16 12:44 UTC, kbressem commented on tests/test_trainer.py
> +        ```
```suggestion

```

2022-11-16 14:15 UTC, kbressem commented
> Fixed mypy but now unit tests are failing. @kbressem Any idea why?

`path_cols` was just a pointer to `image_cols`. So each change to `path_cols` also changes `image_cols`. 

Fixed that. Also made some minor changes on the way

2022-11-16 14:17 UTC, kbressem approved these changes
LGTM now

2022-11-16 16:54 UTC, merged

2022-11-16 16:54 UTC, markus-hinsche commented
Great thanks!